### ISSUE TITLE
"Null expectation context - missing withExpectations?" w/ ScalaTest FunSpec

### ISSUE THREAD

**Issue by SeerUK** [paulbutcher/ScalaMock#117]
Hi, I'm currently trying to create a basic test suite using ScalaTest and wanted to try my hand at mocking too (I'm quite new to Scala so am just wanting to get used to a few things and pin down which libraries I can use to perform common tasks like testing, and mocking etc).

I'm encountering a strange exception when I run my tests, one test succeeds, then all of the following tests fail. I've tried to change how this works a few times to restructured when things are created, and if they're only created once, but I still just get exceptions. 

Here's my tests:

![Tests in IntelliJ IDEA Ultimate](http://i.imgur.com/5zYwjLB.png)

Here's the output:

![Test output from SBT](http://i.imgur.com/Yt8Qkb1.png)

**Comment by eyalroth** [comment]
I've just encountered this as well with `FunSuite`.
It seems to happen when you mock stuff in `before`/`beforeEach`.

A temporary workaround is to define whatever in `before` in a method and calling it at the beginning of each test (in other words, behave like there's no "before" feature).

**Comment by mdirkse** [comment]
+1

**Comment by Tolsi** [comment]
+1

**Comment by agile-jordi** [comment]
+1

**Comment by barkhorn** [comment]
minimal failing example: 

```scala
class CatTest extends FunSuite with BeforeAndAfter with MockFactory {
  var cat: Cat = _

  trait Cat {
    def meow(): String
  }

  before {
    cat = stub[Cat]
    (cat.meow _).when().returns("meow")
  }

  test("meows") {
    cat.meow() === "meow"
  }

  test("meows again") {
    cat.meow() === "meow"
  }
}
```

**Comment by barkhorn** [comment]
working example:

```scala
class CatTest extends FunSuite with BeforeAndAfter with MockFactory {
  var cat: Cat = _

  trait Cat {
    def meow(): String
  }

  before {
    withExpectations {
      cat = stub[Cat]
      (cat.meow _).when().returns("meow")
    }
  }

  test("meows") {
    cat.meow() === "meow"
  }

  test("meows again") {
    cat.meow() === "meow"
  }
}
```

**Comment by TEWatson** [comment]
The example above only works because there is no assertion on the `===`. This code with added asserts looks like this:
```scala
class CatTest extends FunSuite with BeforeAndAfter with MockFactory {
  var cat: Cat = _

  trait Cat {
    def meow(): String
  }

  before {
    withExpectations {
      cat = stub[Cat]
      (cat.meow _).when().returns("meow")
    }
  }

  test("meows") {
    assert(cat.meow() === "meow")
  }

  test("meows again") {
    assert(cat.meow() === "meow")
  }
}
```

Which fails the assertions with `cat.meow()` being equal to null. The problem seems to occur whenever the mock is done within `before{}`. The only way I have been able to get around this is using `OneInstancePerTest` instead of `BeforeAndAfter` and implementing similarly.

**Comment by Woodz** [comment]
@barkhorn can you confirm why this bug was closed? It seems to be confirmed but not fixed?

**Comment by barkhorn** [comment]
Hi, I can't see where the bug is here, so this should remain closed.
To share mocks within a suite, i'd recommend reading up on this page: http://scalamock.org/user-guide/sharing-scalatest/
Using the OneInstancePerTest is the correct way of sharing mocks (or a Fixture, whatever style you like better).

You could kind of use withExpectations too, but not in a before call. A higher order function wrapping around it might work for you.
See here for the implementation, maybe that helps. I would suggest using a Fixture though. https://github.com/paulbutcher/ScalaMock/blob/5fd4e563143d752b9638d32e05defcd8ddb8bb82/shared/src/main/scala/org/scalamock/MockFactoryBase.scala#L47
