### ISSUE TITLE
Typo on mocking style documentation page

### ISSUE THREAD

**Issue by mgrand** [paulbutcher/ScalaMock#128]
On http://scalamock.org/user-guide/mocking_style/
it says
      val heaterMock = mock[HeaterMock]
where is should say
      val heaterMock = mock[Heater]

**Comment by benblack86** [comment]
Instructions on how to contribute to docs would be good, then someone (i.e. me) could do a PR.

**Comment by barkhorn** [comment]
agreed, looking at this

**Comment by paulbutcher** [comment]
The docs are hosted on GitHub Pages in the normal way: Push to the gh-pages branch and it will just work:

https://github.com/paulbutcher/ScalaMock/tree/gh-pages

**Comment by barkhorn** [comment]
changed in 2aeee33c9fdcd8f9f26fe7f60d26984aeb896eab but it looks like the website currently uses static html pages, so changed it in a152a4cf7717e86916e9c1bc2c6052abb0d5fb73 as well.

**Comment by paulbutcher** [comment]
The Scalamock site was put together by @pawel-wiejacha. I believe that he set it up so that you have to build locally with Jekyll because it used plugins that weren't supported by the version of Jekyll GitHub used by default. I've just tried building locally, but it looks like Jekyll has moved on some what since Paweł put it together, and it no longer builds with the most recent version of Jekyll.

Paweł is this something you can shed light on?
