### ISSUE TITLE
ScalaMock doesn't properly override all class members

### ISSUE THREAD

**Issue by marconilanna** [paulbutcher/ScalaMock#129]
ScalaMock doesn't seem to properly override all members of a class. In the example below, no test should pass (no expectations were set), yet the first two pass:

``` scala
import org.scalamock.scalatest.MockFactory
import org.scalatest.FreeSpec

class TestSpec extends FreeSpec with MockFactory {
  "toString" in {
    val test = stub[Test]
    assert(test.toString === "test")
  }

  "hi" in {
    val test = stub[Test]
    assert(test.hi === "test")
  }

  "hello" in {
    val test = stub[Test]
    assert(test.hello === "test")
  }
}

class Test {
  override def toString = "test"
  val hi = "test"
  def hello = "test"
}
```

``` scala
$ sbt test
[info] TestSpec:
[info] - toString
[info] - hi
[info] - hello *** FAILED ***
[info]   null did not equal "test" (CrazyTest.scala:17)
[info] Run completed in 191 milliseconds.
[info] Total number of tests run: 3
[info] Suites: completed 1, aborted 0
[info] Tests: succeeded 2, failed 1, canceled 0, ignored 0, pending 0
[info] *** 1 TEST FAILED ***
```

**Comment by bkowalik** [comment]
1. You cannot mock inherited methods from `java.lang.Object`. It would be nice to narrow it only to `final`s but by now you can't and `toString` has it's proxy in `mock`/`stub`.
2. You cannot mock `val`s and `lazy val`s. I think that it is caused by it's complex nature.
3. `null` in last test case is good because you need to `stub` this method.

So for me everything is good except that maybe some information is missing on the website.

**Comment by barkhorn** [comment]
also see discussion on #148 on val
