### ISSUE TITLE
Set of stubs of a "mockable case class" throws NullPointerException on hashCode

### ISSUE THREAD

**Issue by eyalroth** [paulbutcher/ScalaMock#130]
I have a case class which I'd like to mock/stub:

``` scala
case class Foo(s: String)
```

Since [ScalaMock doesn't support mocks for classes without a default constructor](https://github.com/paulbutcher/ScalaMock/issues/56), I'd have to create a "Mockable" class, and then mock/stub it.

``` scala
class MockableFoo extends Foo("")
stub[MockableFoo]
```

All good, isn't it? well... try to run the following code:

``` scala
Set(stub[MockableFoo], stub[MockableFoo], stub[MockableFoo], stub[MockableFoo], stub[MockableFoo])
```

And it will throw a `NullPointerException` on the `hashCode` method (and trying this with `mock` instead of `stub` will give you another exception, but that's a different issue I assume).

That is weird. Even weirder, it only happens with case classes (not regular classes), specifically if there's a `String` value, and if the `Set` is at least 5 items long!

**Comment by bkowalik** [comment]
This is related to `Set` implementation and generally Scala collections. Every mutable collection for efficiency purposes has it's specialized version. For example `Map` for less than 10 elements is just a simple array. Same goes about `Set`, under 5 elements there is `Set1[A]`, `Set2[A]`, `Set3[A]` and `Set4[A]`. There are made by companion object which implements `ImmutableSetFactory[Set]` which makes for you proper implementation of `Set`. `Set` with under 5 elements does not use `hashCode` to insert element into proper bucket but when you rich up to 5 elements this function is used to insert element.

To conclude, you have to specify `hashCode` to every `stub` or `mock` that you want to insert into collection that exceeds this `optimization threshold` but you can't do it because every method from `java.lang.Object` is filtered out. Normal `class` works because it inherits `hashCode` from `java.lang.Object` but `case class` has it's overriden. Below is detailed explanation why it works for `class` but not for `case class`. To conclude: you can't insert mocks to hashable collections like `Map`s and `Set`s.

I searched very deep into compile time differences between `case class` and `class` and this is what I've found. `toString` and `hashCode` of `case class` is made by `scala.runtime.ScalaRunTime` which is inserted by compiler. It depends on your `case class` shape but generally it is widely used also in `class` for example `toString`. You can inspect youself [scala.runtime.ScalaRunTime](https://github.com/scala/scala/blob/2.11.x/test/instrumented/library/scala/runtime/ScalaRunTime.scala) I believe that it uses runtime reflection and other methods that are not defined in mock. You can check youself by compiling `scala -Xprint:icode Foo.scala` with `class Foo(a: Int)` and then change it to `case class`/`Int` to `AnyRef`.

**Comment by paulbutcher** [comment]
That's a great piece of detective work, @bkowalik. Thanks!
