### ISSUE TITLE
Mock and stub in asynchronous testing

### ISSUE THREAD

**Issue by Maatary** [paulbutcher/ScalaMock#140]
Hi I would to test the collaboration of some object with an actor.

I wonder if there is a way to asynchronously testing expectations or verification ?

Maybe there is some pattern for that ?

The point is I am using persistent actor and can not perform a single threaded test.

Any recommendation ?

**Comment by bkowalik** [comment]
Hi!

What I would do is create mock/stub with `anyNumberOfTimes()` so that you can call it any number of times. If you want to record sequence of events than it is a bit harder because in multithreaded environment you cannot reason about execution order unless you have one actor not whole router for example.

If you want you can also create mock/stub that uses `where` as in this example taken from ScalaMock [website](http://scalamock.org/user-guide/features/):
```
(myMock.sendMessage _).expects(where { (receiver: Player, message: Message) => 
    receiver.name.startsWith("A")
}) 
```

These are the ways that I would do but it feel like integration test for me.
