### ISSUE TITLE
'Unexpected call' throwed when define mock as def

### ISSUE THREAD

**Issue by kamijin-fanta** [paulbutcher/ScalaMock#197]
*If you want to discuss a new feature, please ignore/clear this form.*

### ScalaMock Version (e.g. 3.5.0)

`3.6.0`

### Scala Version (e.g. 2.12)

`2.12.2`

### Runtime (JVM or JS)

`JVM`

### Please describe the expected behavior of the issue

Even if mock is defined with val/def, it behaves in the same way.

### Please provide a description of what actually happens

```
[info] UnexpectedCallSpec:
[info] - val
[info] - def *** FAILED ***
[info]   Unexpected call: <mock-3> Example.foo()
[info]
[info]   Expected:
[info]   inAnyOrder {
[info]     <mock-2> Example.foo() once (never called - UNSATISFIED)
[info]   }
[info]
[info]   Actual:
[info]     <mock-3> Example.foo() (Option.scala:121)
```

### Reproducible Test Case

Please provide a minimised code snippet that fails, ideally, written as a failing test case in ScalaTest.
This will help us a lot in diagnosing the problem and work on a fix.
If the issue is more complex or requires configuration, please provide a link to a project on Github that reproduces the issue.

```scala
class UnexpectedCallSpec extends FunSpec with Matchers with MockFactory {

  trait Example {
    def foo() = "foo"
  }

  it("val") { // ok
    val valFooMock = mock[Example]
    (valFooMock.foo _).expects().returning("foo mock")
    valFooMock.foo() shouldEqual "foo mock"
  }
  it("def") { // ng: Unexpected call: <mock-3> Example.foo()
    def defFooMock = mock[Example]
    (defFooMock.foo _).expects().returning("foo mock")
    defFooMock.foo() shouldEqual "foo mock"
  }

}
```

```scala
// build.sbt
libraryDependencies ++= Seq(
  "org.scalatest" %% "scalatest" % "3.0.1" % Test,
  "org.scalamock" %% "scalamock-scalatest-support" % "3.6.0" % Test,
)
```

**Comment by barkhorn** [comment]
Hi @kamijin-fanta - unfortunately your expectation of `def` and `val` behaving identically is flawed:

In Scala, a `val` is an immutable variable/field, so each reference to it will return the exact same object.
A `def` is a method, so each reference will cause the body of the method to be invoked again.
In this case, this means that each time a new mock will be generated.
So the second test case - `it("def")` is not valid and it is not actually a bug but expected behaviour.

Hope that clears things up for you :)

(same question as #194)

**Comment by kamijin-fanta** [comment]
sorry I could not find my old question.
I read and understood the class file now. Thank you!
