### ISSUE TITLE
Question: Mocking PartialFunctions

### ISSUE THREAD

**Issue by pjan** [paulbutcher/ScalaMock#95]
Hi,

I was wondering whether there's a right and/or easy method to mock a `PartialFunction` so it behaves in a similar way as a `mockFunction`.

I currently do it all manually, but have a suspicion this is a bit too involved. Example:

``` scala
val mock = MockFunction[Int, Unit]

val mockPartial: PartialFunction[Int, Unit] = {
    case i: Int => mock(i)
}

mockPartial(3)

mock.expects(3)
```

Thanks a lot! Much appreciated.

**Comment by paulbutcher** [comment]
The following *should* work:

      val m = mock[PartialFunction[Int, Int]]
      (m.apply _).expects(0).returning(1)
      assertResult(1) { m(0) }

However it doesn't because the `mock[PartialFunction[Int, Int]]` fails with:
```
type mismatch;
[error]  found   : x.type (with underlying type A1)
[error]  required: A1
[error]       val m = mock[PartialFunction[Int, Int]]
[error]                   ^
```

The good news is that this does work in the in-progress ScalaMock4 branch that I'm currently working on. Note the nicer syntax too:

       val m = mock[PartialFunction[Int, Int]]
       m.expects.apply(0).returning(1)
       assertResult(1) { m(0) }

**Warning:** it's definitely not ready for production use yet and may never see the light of day at all, depending on whether I manage to fix some of the outstanding macro-related issues.

**Comment by barkhorn** [comment]
it's possible in in scalamock 3 too:

```scala
    val m = mockFunction[Int, String]
    val mp = new PartialFunction[Int, String] {
      def isDefinedAt(x: Int) = true
      def apply(v1: Int) = m(v1)
    }

    m expects 42 returning "foo" once()

    mp(42) shouldBe "foo"
```

**Comment by barkhorn** [comment]
closing this as it is already possible, although not terribly concise.
